### ISSUE TITLE
How to login or update user details

### ISSUE THREAD

**Issue by ajmal-ahmed** [Kommunicate-io/kommunicate-chatbot-plugin#4]
Does this package offers login and update user functionalities of kommunicate?

**Comment by kommunicateaejaz** [comment]
Hello Ajmal,

It is documented here: https://docs.kommunicate.io/docs/web-authentication#user-details

**Comment by ajmal-ahmed** [comment]
by reading at the documentation [I ended up creating a react component](https://docs.kommunicate.io/docs/web-installation#method-2-by-creating-kommunicate-chat-component) instead of using this plugin package.

**Comment by kommunicateaejaz** [comment]
Okay, is this what you were looking?

**Comment by ajmal-ahmed** [comment]
No, I was looking whether there is any option within the plugin package to manage events instead of using it via external script

**Comment by panwaranuj01** [comment]
@ajmal-ahmed You can pass the same setting in package also.

like you mentioned you need to capture events

```
Kommunicate.init("kommunicate-support", {
  automaticChatOpenOnNavigation: true,
  popupWidget: true,
  onInit: () => {
    var events = {
      "onMessageSent": (e) => {
        console.log(e)
      }
    }
    window.Kommunicate.subscribeToEvents(events);
  }
});

```
